# This is a basic workflow to help you get started with Actions

name: Build project

# Controls when the action will run. 
on:
  pull_request: {}
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
jobs:
  buildForSomePlatforms:
    name: Build for StandaloneWindows64  on version 2020.2.4f1
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: mk protobuf dir
        run: mkdir .\Assets\generatedFiles\Scripts\Common\Data\Protobuf        
      - name: compile protobuf 1
        run: .\Assets\Editor\protoc\bin\windows-x64\protoc.exe -I .\Assets\Editor\protoc\include -I .\Assets\Scripts\Common\Data\Protobuf --csharp_out=.\Assets\generatedFiles\Scripts\Common\Data\Protobuf --grpc_out=.\Assets\generatedFiles\Scripts\Common\Data\Protobuf --plugin=protoc-gen-grpc=.\Assets\Editor\protoc\bin\windows-x64\grpc_csharp_plugin.exe .\Assets\Scripts\Common\Data\Protobuf\MapTypes.proto
      - name: compile protobuf 2
        run: .\Assets\Editor\protoc\bin\windows-x64\protoc.exe -I .\Assets\Editor\protoc\include -I .\Assets\Scripts\Common\Data\Protobuf --csharp_out=.\Assets\generatedFiles\Scripts\Common\Data\Protobuf --grpc_out=.\Assets\generatedFiles\Scripts\Common\Data\Protobuf --plugin=protoc-gen-grpc=.\Assets\Editor\protoc\bin\windows-x64\grpc_csharp_plugin.exe .\Assets\Scripts\Common\Data\Protobuf\UpdateMapService.proto
      - name: Build unity player
        run: |
        'C:\Program Files\Unity\Hub\Editor\2020.2.4f1\Editor\Unity.exe' -quit -accept-apiupdate -batchmode -serial F4-X8VG-AMQS-HB73-646U-8YPY -username 'p.krasnov@dioram.ai' -password 'USSEnterprise1701' -projectPath D:\Elektronik-Tools-2.0\ -buildWindows64Player .\Build\Elektronik.exe
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
