# This is a basic workflow to help you get started with Actions

name: Build project

# Controls when the action will run. 
on:
  pull_request: {}
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  UNITY_USERNAME: ${{ secrets.UNITY_USERNAME }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
jobs:
  buildForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.2.2f1
        targetPlatform:
          - StandaloneWindows64 
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: yukiarrr/unity-build-action@v0.6.1
        with:
          unity-version: 2020.2.2f1
          unity-username: ${{ secrets.UNITY_USERNAME }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-serial: ${{ secrets.UNITY_SERIAL }}
          build-target: Win64
      - uses: actions/upload-artifact@v1
        with:
          name: Output
          path: Output
